# Generated by Django 6.0.2 on 2026-03-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('RECEPTION', 'Receptionist'), ('LAB', 'Lab Technician'), ('PHARMACY', 'Pharmacist')], default='ADMIN', max_length=20),
        ),
    ]
