# Generated by Django 6.0.2 on 2026-03-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0007_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='fee',
            field=models.IntegerField(default=500),
        ),
    ]
