# Generated by Django 6.0.2 on 2026-03-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0010_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('RECEPTION', 'Reception'), ('LAB', 'Lab Technician'), ('PHARMACY', 'Pharmacist'), ('PATIENT', 'Patient')], default='ADMIN', max_length=20),
        ),
    ]
