# Generated by Django 6.0.2 on 2026-04-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0014_patient_medical_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
    ]
