# Generated by Django 6.0.2 on 2026-04-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0017_remove_appointment_fee_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
