# Generated by Django 6.0.2 on 2026-04-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0018_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('COMPLETED', 'COMPLETED')], default='Pending', max_length=20),
        ),
    ]
