# Generated by Django 6.0.2 on 2026-04-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0020_prescription_created_at_prescription_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
