# Generated by Django 6.0.2 on 2026-04-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0022_alter_appointment_status_alter_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
