# Generated by Django 6.0.2 on 2026-04-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0023_alter_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='abnormal_flag',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Critical', 'Critical')], default='Normal', max_length=20),
        ),
    ]
